# /etc/zsh/zprofile: system-wide .zprofile file for zsh(1).
#
# This file is sourced only for login shells (i.e. shells
# invoked with "-" as the first character of argv[0], and
# shells invoked with the -l flag.)
#
# Global Order: zshenv, zprofile, zshrc, zlogin

# ubuntu-development: git global identity from GIT_USER_NAME / GIT_USER_EMAIL
if [ -r /usr/local/share/ubuntu-development/git-config-global-from-env.sh ]; then . /usr/local/share/ubuntu-development/git-config-global-from-env.sh; fi
